### ISSUE TITLE
記事作成時にエラーアラートが出てくる要因特定と、修正

### ISSUE THREAD

**Issue by fuga-naito23** [yasunamiura/tech_share#123]
[![Screenshot from Gyazo](https://gyazo.com/e76eb99df3ea8e7755dff4f2e0c83029/raw)](https://gyazo.com/e76eb99df3ea8e7755dff4f2e0c83029)

**Comment by KazYam1001** [comment]
仮説
・getリクエストで投稿内容をparamsとして送っているため、リクエストURLが長すぎる

対策
・ajaxでプレビュー表示する際にpostでリクエストを送る
