### ISSUE TITLE
articleのデータベース設計

### ISSUE THREAD

**Issue by yasunamiura** [yasunamiura/tech_share#29]
READMEに書いているデータベースを実装していいのか話し合いたいです！

**Comment by iy06** [comment]
[tech_share.pdf](https://github.com/yasunamiura/tech_share/files/4007800/tech_share.pdf)
僕の頭の中ではこんな感じのデータベース設計になっています。
カラムは記述していません。
アソシエーションだけを記述しています！

**Comment by yasunamiura** [comment]
![iOS の画像](https://user-images.githubusercontent.com/52514431/71572885-89446780-2b24-11ea-9ec2-b7ada4736be7.jpg)
コメントテーブルの定義が違っていたので描いてみました！

**コメントテーブルについて**
ナレッジ記事(article)についてコメントをするためのテーブルという位置づけです
