### ISSUE TITLE
ユーザー管理機能について

### ISSUE THREAD

**Issue by yasunamiura** [yasunamiura/tech_share#31]
as is:　今どのような状態か？

誰でも投稿・編集できるが誰がやったのか分からない

to be:　どういう状態が望ましいか？

情報の信頼性を高めるため、投稿者を明らかにする

**いい案あったらコメントくださーい**

**Comment by iy06** [comment]
as is: 
ユーザー機能を実装していないので、誰でも投稿できる。

to be: 
ユーザー登録をした人だけ、投稿とコメント、質問と回答ができる。
名前だけではなくアイコンをつける。

**Comment by yasunamiura** [comment]
-誰が書いたか分かる
-Basic認証つける

**Comment by yasunamiura** [comment]
-google認証
