### ISSUE TITLE
user検索機能について

### ISSUE THREAD

**Issue by fuga-naito23** [yasunamiura/tech_share#60]
ユーザー検索機能を実装する必要がある。

**Comment by yasunamiura** [comment]
内藤さん実装お願いします！

**Comment by KazYam1001** [comment]
## 方針
- 検索ボックスを改造し「ナレッジ検索」「ユーザー検索」の2つを選べる様にする
- コントローラーで条件分岐し、ナレッジ検索なら従来の検索機能が動くようにする
- ユーザー検索なら入力された文字列からユーザー名を検索する
- search/index.json.jbuilder でユーザー名とIDをJSONとして返す
- JSのdone内で、ユーザー名と各ユーザーのマイページへのリンクが含まれているHTML組み立てる
- 上記HTMLをappendする
