### ISSUE TITLE
メールアドレスのバリデーション

### ISSUE THREAD

**Issue by fuga-naito23** [yasunamiura/tech_share#69]
[課題]
divの社員以外の人がナレッジサイトを見ることができる
→受講生、退職者

[解決策]
手順①登録メールアドレスに「@di-v.co.jp」のバリデーションを設定する。
手順②登録されたメールアドレスに確認用のメールを送り実在するかどうかを判定する。

**Comment by iy06** [comment]
/\A[a-zA-Z0-9_\#!$%&`'*+\-{|}~^\/=?\.]+@di-v.co.jp/
